header_pages:
 - index.md
 - coding.md
 - about.md

style: dark # dark (default) or light

permalink: /:categories/:title

#google_analytics: UA-NNNNNNNN-N
#footer: 'follow us on <a href="https://twitter.com/">twitter</a>'
#listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
